export const coursesData = [
    {
      id: 1,
      title: "Complete React Development Course",
      instructor: "John Davis",
      instructorId: "inst_001",
      category: "Programming",
      enrollments: 1250,
      price: 89.99,
      status: "published",
      approvalStatus: "approved",
      rating: 4.8,
      duration: "40 hours",
      createdDate: "2024-01-15",
      submittedDate: "2024-01-10",
      reviewedDate: "2024-01-12",
      reviewedBy: "Admin User",
      adminNotes: "Great course content, approved for publication",
      thumbnail: "/placeholder.svg?height=200&width=300",
      description: "Comprehensive React course covering hooks, state management, and modern development practices.",
    },
    {
      id: 2,
      title: "Advanced Python Programming",
      instructor: "Sarah Wilson",
      instructorId: "inst_002",
      category: "Programming",
      enrollments: 890,
      price: 79.99,
      status: "published",
      approvalStatus: "approved",
      rating: 4.6,
      duration: "35 hours",
      createdDate: "2024-01-20",
      submittedDate: "2024-01-18",
      reviewedDate: "2024-01-19",
      reviewedBy: "Admin User",
      adminNotes: "Excellent content structure and delivery",
      thumbnail: "/placeholder.svg?height=200&width=300",
      description: "Deep dive into advanced Python concepts and frameworks.",
    },
    {
      id: 3,
      title: "Machine Learning Fundamentals",
      instructor: "Mike Johnson",
      instructorId: "inst_003",
      category: "Data Science",
      enrollments: 0,
      price: 99.99,
      status: "draft",
      approvalStatus: "pending",
      rating: 0,
      duration: "50 hours",
      createdDate: "2024-02-01",
      submittedDate: "2024-02-01",
      reviewedDate: null,
      reviewedBy: null,
      adminNotes: "Awaiting review",
      thumbnail: "/placeholder.svg?height=200&width=300",
      description: "Introduction to machine learning algorithms and applications.",
    },
    {
      id: 4,
      title: "Web Design Basics",
      instructor: "Emily Chen",
      instructorId: "inst_004",
      category: "Design",
      enrollments: 0,
      price: 59.99,
      status: "draft",
      approvalStatus: "rejected",
      rating: 0,
      duration: "25 hours",
      createdDate: "2024-01-25",
      submittedDate: "2024-01-25",
      reviewedDate: "2024-01-26",
      reviewedBy: "Admin User",
      adminNotes: "Content needs significant improvement. Please revise and resubmit.",
      thumbnail: "/placeholder.svg?height=200&width=300",
      description: "Learn the basics of web design and user interface principles.",
    },
    {
      id: 5,
      title: "Digital Marketing Strategy",
      instructor: "Alex Brown",
      instructorId: "inst_005",
      category: "Marketing",
      enrollments: 0,
      price: 69.99,
      status: "draft",
      approvalStatus: "pending",
      rating: 0,
      duration: "30 hours",
      createdDate: "2024-02-05",
      submittedDate: "2024-02-05",
      reviewedDate: null,
      reviewedBy: null,
      adminNotes: "Under review",
      thumbnail: "/placeholder.svg?height=200&width=300",
      description: "Comprehensive guide to digital marketing strategies and tools.",
    },
  ];